steps:
# Build Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/temp-converter:$TAG_NAME', '.']
# Push Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/temp-converter:$TAG_NAME'] 
  
