---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: converter-deployment
  labels:
    app: converter
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: converter
      tier: frontend
  template:
    metadata:
      labels:
        app:  converter
        tier: frontend
    spec:
      containers:
      - name: converter
        image: gcr.io/doug-rehnstrom/converter:v1.0
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "256Mi"
            cpu: "0.1"
          limits:
            memory: "512Mi"
            cpu: "0.5"

---

apiVersion: v1
kind: Service
metadata:
  name: converter-deployment-lb
  labels:
    app: converter
    tier: frontend-lb
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: converter
    tier: frontend
 
---

apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: converter-deployment-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v2beta1
    kind: Deployment
    name: converter-deployment
  minReplicas: 3
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 60