# This is a basic workflow to help you get started with Actions

name: Run Unit Tests Workflow

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  unit-test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Just say hello
        run: echo Hello Action. Hope this works.

      # Runs a set of commands using the runners shell
      - name: Check the environment
        run: |
          echo See if the repo was cloned...
          ls -a
          echo See if Python is installed...
          python --version
          pip --version

      - name: Install Requirements
        run: |
          echo Run pip install...
          pip install -r requirements.txt

      - name: Run unit tests
        run: |
          echo Run unit tests...
          pytest
